# Generated by Django 5.2.17 on 2026-09-25 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0041_alter_brandmapping_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=255, unique=True)),
                ("sender", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("body_text", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("needs_review", "Needs review"),
                            ("suggested", "Suggested"),
                            ("uploaded", "Uploaded"),
                            ("ignored", "Ignored"),
                        ],
                        default="new",
                        max_length=14,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("unknown_sender", "Unknown sender"),
                            ("link_only", "Link only"),
                            ("no_tc_attachment", "No TC attachment"),
                            ("columns_unrecognised", "Columns unrecognised"),
                            ("pdf_disagreement", "PDF readings disagree"),
                            ("shared_tc", "Shared TC"),
                            ("no_schedule", "No schedule"),
                            ("multiple_schedules", "Multiple schedules"),
                            ("conflict", "Conflict"),
                            ("schedule_frozen", "Schedule frozen"),
                            ("tc_already_exists", "TC already exists"),
                            ("low_brand_overlap", "Low brand overlap"),
                            ("date_out_of_range", "Date out of range"),
                            ("row_mismatch", "Row mismatch"),
                            ("suspicious_instruction", "Suspicious instruction"),
                            ("tool_error", "Tool error"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AllowedSender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InboundAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("file", models.FileField(blank=True, upload_to="intake/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("needs_review", "Needs review"),
                            ("suggested", "Suggested"),
                            ("uploaded", "Uploaded"),
                            ("ignored", "Ignored"),
                        ],
                        default="new",
                        max_length=14,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("unknown_sender", "Unknown sender"),
                            ("link_only", "Link only"),
                            ("no_tc_attachment", "No TC attachment"),
                            ("columns_unrecognised", "Columns unrecognised"),
                            ("pdf_disagreement", "PDF readings disagree"),
                            ("shared_tc", "Shared TC"),
                            ("no_schedule", "No schedule"),
                            ("multiple_schedules", "Multiple schedules"),
                            ("conflict", "Conflict"),
                            ("schedule_frozen", "Schedule frozen"),
                            ("tc_already_exists", "TC already exists"),
                            ("low_brand_overlap", "Low brand overlap"),
                            ("date_out_of_range", "Date out of range"),
                            ("row_mismatch", "Row mismatch"),
                            ("suspicious_instruction", "Suspicious instruction"),
                            ("tool_error", "Tool error"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                (
                    "suggested_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.schedule",
                    ),
                ),
                (
                    "tc_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.transmissionreport",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="intake.inboundemail",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email", "sha256"), name="intake_attachment_unique"
                    )
                ],
            },
        ),
    ]
