# Generated by Django 5.2.17 on 2026-09-25 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_alter_brandmapping_duration_and_more"),
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allowedsender",
            options={"ordering": ["email_or_domain"]},
        ),
        migrations.AlterModelOptions(
            name="inboundattachment",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="inboundemail",
            options={"ordering": ["-received_at", "-id"]},
        ),
        migrations.RemoveField(
            model_name="allowedsender",
            name="account",
        ),
        migrations.RemoveField(
            model_name="allowedsender",
            name="email",
        ),
        migrations.RemoveField(
            model_name="allowedsender",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="allowedsender",
            name="name",
        ),
        migrations.RemoveField(
            model_name="inboundattachment",
            name="file",
        ),
        migrations.AddField(
            model_name="allowedsender",
            name="accounts",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="core.account"
            ),
        ),
        migrations.AddField(
            model_name="allowedsender",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="allowedsender",
            name="channel_hint",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="allowedsender",
            name="email_or_domain",
            field=models.CharField(default="", max_length=254, unique=True),
            preserve_default=False,   # AllowedSender is empty everywhere (Phase 1 table, never filled)
        ),
        migrations.AddField(
            model_name="allowedsender",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="inboundattachment",
            name="content",
            field=models.BinaryField(blank=True, default=b""),
        ),
        migrations.AddField(
            model_name="inboundattachment",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inboundattachment",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="intake.inboundattachment",
            ),
        ),
        migrations.AddField(
            model_name="inboundattachment",
            name="evidence",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="inboundattachment",
            name="ext",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="inboundattachment",
            name="llm_hint_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.schedule",
            ),
        ),
        migrations.AddField(
            model_name="inboundattachment",
            name="llm_verdict",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="inboundattachment",
            name="note",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="inboundattachment",
            name="purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inboundattachment",
            name="rule_verdict",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="inboundemail",
            name="imap_uid",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="inboundemail",
            name="purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inboundattachment",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("unknown_sender", "Unknown sender"),
                    ("link_only", "Link only"),
                    ("no_tc_attachment", "No TC attachment"),
                    ("columns_unrecognised", "Columns unrecognised"),
                    ("pdf_disagreement", "PDF readings disagree"),
                    ("shared_tc", "Shared TC"),
                    ("no_schedule", "No schedule"),
                    ("multiple_schedules", "Multiple schedules"),
                    ("conflict", "Conflict"),
                    ("schedule_frozen", "Schedule authorised"),
                    ("tc_already_exists", "TC already exists"),
                    ("low_brand_overlap", "Low brand overlap"),
                    ("date_out_of_range", "Date out of range"),
                    ("row_mismatch", "Row mismatch"),
                    ("suspicious_instruction", "Suspicious instruction"),
                    ("tool_error", "Tool error"),
                    ("duplicate_active_number", "Duplicate active schedule number"),
                    ("schedule_locked", "Schedule locked"),
                    ("too_large", "Attachment too large"),
                    ("foreign_brands", "Other clients' brands"),
                    ("llm_disagrees", "Assistant disagrees with rules"),
                    ("duplicate_attachment", "Duplicate attachment"),
                    ("unsupported_type", "Unsupported file type"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="inboundattachment",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("processing", "Processing"),
                    ("needs_review", "Needs review"),
                    ("suggested", "Proposed"),
                    ("uploaded", "Uploaded"),
                    ("ignored", "Ignored"),
                    ("duplicate", "Duplicate"),
                    ("rejected", "Rejected"),
                ],
                default="new",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="inboundemail",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("unknown_sender", "Unknown sender"),
                    ("link_only", "Link only"),
                    ("no_tc_attachment", "No TC attachment"),
                    ("columns_unrecognised", "Columns unrecognised"),
                    ("pdf_disagreement", "PDF readings disagree"),
                    ("shared_tc", "Shared TC"),
                    ("no_schedule", "No schedule"),
                    ("multiple_schedules", "Multiple schedules"),
                    ("conflict", "Conflict"),
                    ("schedule_frozen", "Schedule authorised"),
                    ("tc_already_exists", "TC already exists"),
                    ("low_brand_overlap", "Low brand overlap"),
                    ("date_out_of_range", "Date out of range"),
                    ("row_mismatch", "Row mismatch"),
                    ("suspicious_instruction", "Suspicious instruction"),
                    ("tool_error", "Tool error"),
                    ("duplicate_active_number", "Duplicate active schedule number"),
                    ("schedule_locked", "Schedule locked"),
                    ("too_large", "Attachment too large"),
                    ("foreign_brands", "Other clients' brands"),
                    ("llm_disagrees", "Assistant disagrees with rules"),
                    ("duplicate_attachment", "Duplicate attachment"),
                    ("unsupported_type", "Unsupported file type"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="inboundemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("processing", "Processing"),
                    ("needs_review", "Needs review"),
                    ("suggested", "Proposed"),
                    ("uploaded", "Uploaded"),
                    ("ignored", "Ignored"),
                    ("duplicate", "Duplicate"),
                    ("rejected", "Rejected"),
                ],
                default="new",
                max_length=14,
            ),
        ),
    ]
