# Generated by Django 5.2.11 on 2026-03-01 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_channel_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringdata",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoring_data",
                to="core.account",
            ),
        ),
    ]
