# Generated by Django 5.2.11 on 2026-03-01 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_account_to_monitoring"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        help_text="Brand name as it appears in the Schedule file",
                        max_length=200,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        help_text="Theme name as it appears in LMRB (Advt_Theme) or MapOnline (Theme)",
                        max_length=200,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_mappings",
                        to="core.account",
                    ),
                ),
            ],
            options={
                "ordering": ["brand", "theme"],
                "unique_together": {("account", "brand", "theme")},
            },
        ),
    ]
