# Generated by Django 5.2.11 on 2026-03-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_schedulerow_lmrbrow_matchresult_fks"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lmrbrow",
            new_name="core_lmrbro_account_ba569e_idx",
            old_name="core_lmrbro_account_idx1",
        ),
        migrations.RenameIndex(
            model_name="schedulerow",
            new_name="core_schedu_account_099224_idx",
            old_name="core_schedu_account_idx1",
        ),
        migrations.RenameIndex(
            model_name="schedulerow",
            new_name="core_schedu_account_c4860f_idx",
            old_name="core_schedu_account_idx2",
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="ad_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="ads",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="ads_in_brk",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="advertiser",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="brk_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="day",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="lng",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="pos_in_brk",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="product",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="product_group",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="prog_time",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="program",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="lmrbrow",
            name="tot_ads",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="monitoringdata",
            name="file_group_id",
            field=models.CharField(blank=True, default="", max_length=36),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
