# Generated by Django 5.2.11 on 2026-03-03 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_lmrbrow_extra_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="brandmapping",
            name="tc_theme",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Theme/Product name as it appears in the Transmission Certificate (TC) file",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="TransmissionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=200)),
                ("month", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="tc/")),
                ("original_filename", models.CharField(max_length=255)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tc_reports",
                        to="core.account",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tc_reports",
                        to="core.schedule",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_tc",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SummaryReportMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=200)),
                ("month", models.CharField(max_length=50)),
                (
                    "supplier_invoice_no",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("po_no", models.CharField(blank=True, default="", max_length=200)),
                (
                    "invoice_no",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "prepared_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "checked_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "authorised_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_metas",
                        to="core.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("account", "channel", "month")},
            },
        ),
        migrations.CreateModel(
            name="TCRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("programme", models.CharField(blank=True, default="", max_length=500)),
                ("tc_theme", models.CharField(max_length=500)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("aired_time", models.CharField(max_length=30)),
                ("dedup_key", models.CharField(max_length=64, unique=True)),
                (
                    "is_schedule_matched",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "is_lmrb_confirmed",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("is_extra", models.BooleanField(db_index=True, default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.account"
                    ),
                ),
                (
                    "matched_lmrb",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tc_confirmations",
                        to="core.lmrbrow",
                    ),
                ),
                (
                    "matched_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tc_matches",
                        to="core.schedulerow",
                    ),
                ),
                (
                    "tc_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="core.transmissionreport",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "aired_time"],
                "indexes": [
                    models.Index(
                        fields=["account", "channel", "date"],
                        name="core_tcrow_account_496f36_idx",
                    ),
                    models.Index(
                        fields=["account", "channel", "is_schedule_matched"],
                        name="core_tcrow_account_4b0995_idx",
                    ),
                ],
            },
        ),
    ]
