# Generated by Django 5.2.12 on 2026-03-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_extend_manual_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_superseded",
            field=models.BooleanField(default=False),
        ),
    ]
