# Generated by Django 5.2.12 on 2026-03-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulerow",
            name="sponsorship_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Type of sponsorship e.g. BB, Tag, Opening/Closing — set at upload",
                max_length=100,
            ),
        ),
    ]
