# Generated by Django 5.2.12 on 2026-03-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_channelofficer"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelofficer",
            name="is_whatsapp_registered",
            field=models.BooleanField(
                default=False,
                help_text="True once the officer has sent their first WhatsApp message to the business number.",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="category",
            field=models.CharField(
                choices=[
                    ("reconciliation", "Reconciliation"),
                    ("tc_parsing", "TC File Parsing"),
                    ("lmrb_parsing", "LMRB / MapOnline File Parsing"),
                    ("whatsapp", "WhatsApp Notifications"),
                ],
                default="reconciliation",
                max_length=50,
            ),
        ),
    ]
