# Generated by Django 5.2.12 on 2026-03-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_channelofficer_whatsapp_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("matched", "Matched"),
                    ("programme_mismatch", "Programme Mismatch"),
                    ("late_telecast", "Late Telecast"),
                    ("not_aired", "Not Aired"),
                    ("no_mapping", "No Brand Mapping"),
                    ("manual_match", "Manually Matched"),
                    ("extra_aired", "Extra Aired"),
                ],
                max_length=30,
            ),
        ),
    ]
