# Generated by Django 5.2.15 on 2026-06-23 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_spotnote_unread_spotnotification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lmrbrow",
            name="is_tc_lmrb_matched",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="tcrow",
            name="is_tc_lmrb_matched",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="category",
            field=models.CharField(
                choices=[
                    ("reconciliation", "Reconciliation"),
                    ("tc_parsing", "TC File Parsing"),
                    ("lmrb_parsing", "LMRB / MapOnline File Parsing"),
                    ("whatsapp", "WhatsApp Notifications"),
                    ("email", "Email Notifications"),
                    ("display", "Display & Export"),
                ],
                default="reconciliation",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="TcLmrbMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=200)),
                ("month", models.CharField(max_length=50)),
                (
                    "match_type",
                    models.CharField(
                        choices=[("auto", "Auto"), ("manual", "Manual")],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tc_lmrb_matches",
                        to="core.account",
                    ),
                ),
                (
                    "lmrb_row",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tc_lmrb_match",
                        to="core.lmrbrow",
                    ),
                ),
                (
                    "matched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tc_lmrb_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tc_row",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tc_lmrb_match",
                        to="core.tcrow",
                    ),
                ),
            ],
            options={
                "ordering": ["tc_row__date", "tc_row__aired_time"],
                "indexes": [
                    models.Index(
                        fields=["account", "channel", "month"],
                        name="core_tclmrb_account_77ee0b_idx",
                    )
                ],
            },
        ),
    ]
