# Generated by Django 5.2.15 on 2026-07-08 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_lmrbrow_is_tc_lmrb_matched_tcrow_is_tc_lmrb_matched_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TcLmrbThemeMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tc_theme", models.CharField(max_length=300)),
                ("tc_duration", models.PositiveIntegerField(blank=True, null=True)),
                ("lmrb_theme", models.CharField(max_length=300)),
                ("lmrb_duration", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tc_lmrb_theme_maps",
                        to="core.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tc_lmrb_theme_maps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["tc_theme", "tc_duration"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "tc_theme", "tc_duration"),
                        name="uniq_tclmrbthememap_scope",
                    )
                ],
            },
        ),
    ]
