# Generated by Django 5.2.15 on 2026-07-15 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_tclmrbthememap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodSponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=200)),
                ("month", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=200)),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="LMRB Advt_Theme to count directly; blank = resolve via BrandMapping.brand",
                        max_length=300,
                    ),
                ),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("planned_count", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("schedule", "From schedule")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_sponsorships",
                        to="core.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="period_sponsorships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["channel", "brand", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="PeriodSponsorshipMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lmrb_row",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_sponsorship_match",
                        to="core.lmrbrow",
                    ),
                ),
                (
                    "period_sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="core.periodsponsorship",
                    ),
                ),
            ],
            options={
                "ordering": ["lmrb_row__date", "lmrb_row__advt_time"],
            },
        ),
        migrations.AddIndex(
            model_name="periodsponsorship",
            index=models.Index(
                fields=["account", "channel", "month"],
                name="core_period_account_7cd22a_idx",
            ),
        ),
    ]
