# Generated by Django 5.2.16 on 2026-07-21 15:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_periodsponsorship_periodsponsorshipmatch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Client logo shown on the Media Reconciliation Report.",
                null=True,
                upload_to="client_logos/",
            ),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="agency_pct",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("10.75"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="cag_pct",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="campaign",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="client_pct",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("4.25"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="date_of_reconciliation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="deviation_notes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="media",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="media_house_pct",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("85"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="medium",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="schedule_value",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="specification",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="sscl_pct",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("2.5"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="supplier_reference",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="summaryreportmeta",
            name="vat_pct",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("18"), max_digits=6
            ),
        ),
    ]
