# Generated by Django 5.1 on 2026-07-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_client_logo_summaryreportmeta_agency_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="summaryreportmeta",
            name="spot_labels",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
