# Generated by Django 5.1 on 2026-07-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_summaryreportmeta_spot_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "message",
                    models.TextField(help_text="Shown in the banner. Plain text."),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("update", "Update"),
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                        ],
                        default="update",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Uncheck to hide the banner without deleting it.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
