# Generated by Django 5.2.16 on 2026-07-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_tcchannelprompt"),
        ("core", "0038_sitenotification"),
    ]

    operations = []
