# Generated by Django 5.1 on 2026-08-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_scheduletemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandmapping",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duration in seconds (optional - leave blank to match any duration)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tv", "TV"),
                    ("radio", "Radio"),
                    ("press", "Press"),
                    ("other", "Other"),
                ],
                default="",
                help_text="TV / Radio / Press - auto-detected from channel name prefix at upload",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="schedulerow",
            name="product",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Product name - should match LMRB Product field",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="schedulerow",
            name="sponsorship_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Type of sponsorship e.g. BB, Tag, Opening/Closing - set at upload",
                max_length=100,
            ),
        ),
    ]
