# Generated by Django 5.2.12 on 2026-03-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_whatsapp_channel_officer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_whatsapp_registered",
            field=models.BooleanField(
                default=False,
                help_text="True once the user has replied to their WhatsApp welcome message.",
            ),
        ),
    ]
