# Generated by Django 5.2.13 on 2026-04-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_whatsapp_registered"),
        ("core", "0028_add_client_model_and_user_clients"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="clients",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="core.client"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("team_head", "Team Head"),
                    ("planner", "Planner"),
                    ("operations", "Operations"),
                    ("channel_officer", "Marketing Officer"),
                ],
                default="planner",
                max_length=20,
            ),
        ),
    ]
