# Generated by Django 5.2.16 on 2026-07-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_client_model_and_user_clients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Admin"),
                    ("admin", "Admin"),
                    ("team_head", "Team Head"),
                    ("planner", "Planner"),
                    ("operations", "Operations"),
                    ("channel_officer", "Marketing Officer"),
                ],
                default="planner",
                max_length=20,
            ),
        ),
    ]
