# Generated by Django 5.2.17 on 2026-09-25 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0041_alter_brandmapping_duration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Heartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("last_beat", models.DateTimeField()),
                ("detail", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ScopeLockRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.BigIntegerField(unique=True)),
                ("owner", models.CharField(max_length=120)),
                ("acquired_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="AgentAccountOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(blank=True, null=True)),
                (
                    "autonomy_level",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_override",
                        to="core.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("autonomy_level", models.PositiveSmallIntegerField(default=0)),
                ("mapping_threshold", models.FloatField(default=0.92)),
                ("grace_days", models.PositiveSmallIntegerField(default=3)),
                (
                    "upload_debounce_minutes",
                    models.PositiveSmallIntegerField(default=10),
                ),
                (
                    "tc_intake_mode",
                    models.CharField(
                        choices=[
                            ("off", "Off"),
                            ("suggest", "Suggest"),
                            ("auto", "Auto"),
                        ],
                        default="off",
                        max_length=10,
                    ),
                ),
                ("llm_daily_token_cap", models.PositiveIntegerField(default=200000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "agent configuration",
            },
        ),
        migrations.CreateModel(
            name="ScopeState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=200)),
                ("month", models.CharField(max_length=50)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("STILL_AIRING", "Still airing"),
                            ("WAITING_INPUTS", "Waiting for inputs"),
                            ("STANDALONE", "Standalone TC"),
                            ("INGEST_CHECK", "Ingestion check"),
                            ("MAPPING", "Needs mapping"),
                            ("RECONCILING", "Reconciling"),
                            ("VALIDATING", "Validating"),
                            ("DIAGNOSING", "Diagnosing"),
                            ("NEEDS_HUMAN", "Needs a person"),
                            ("READY_FOR_SIGNOFF", "Ready for sign-off"),
                            ("AUTHORISED", "Authorised"),
                        ],
                        default="WAITING_INPUTS",
                        max_length=24,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=64)),
                ("repair_round", models.PositiveSmallIntegerField(default=0)),
                ("lock_baseline", models.IntegerField(blank=True, null=True)),
                ("needs_run", models.BooleanField(default=False)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_scopes",
                        to="core.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sub_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("pending_rows", "Rows pending (Rule 8)"),
                            ("reconciled", "Reconciled"),
                            ("ready", "Ready"),
                            ("authorised", "Authorised"),
                            ("needs_human", "Needs a person"),
                        ],
                        default="waiting",
                        max_length=16,
                    ),
                ),
                ("has_tc", models.BooleanField(default=False)),
                ("matched_count", models.PositiveIntegerField(default=0)),
                ("pending_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_status",
                        to="core.schedule",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="agent.scopestate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dedupe_key", models.CharField(max_length=200, unique=True)),
                ("template_key", models.CharField(max_length=60)),
                ("via", models.CharField(default="whatsapp", max_length=20)),
                ("status", models.CharField(default="queued", max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agent.scopestate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LlmCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose", models.CharField(max_length=40)),
                ("provider", models.CharField(default="anthropic", max_length=20)),
                ("model", models.CharField(blank=True, default="", max_length=80)),
                (
                    "prompt_version",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("outcome", models.CharField(blank=True, default="", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agent.scopestate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cycle", "Cycle"),
                            ("scope", "Scope run"),
                            ("dry_run", "Dry run"),
                            ("golden", "Golden check"),
                            ("audit", "Core audit"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("ok", "OK"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("rolled_back", "Rolled back"),
                        ],
                        default="running",
                        max_length=12,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="agent.scopestate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier", models.PositiveSmallIntegerField(default=0)),
                ("action_type", models.CharField(max_length=40)),
                (
                    "target_model",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("target_pk", models.CharField(blank=True, default="", max_length=40)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True, default="")),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("mapping", "Mapping"),
                            ("alias", "Column alias"),
                            ("manual_match", "Manual match"),
                            ("tolerance", "Tolerance"),
                            ("tc_split", "TC split"),
                            ("tc_link", "TC link"),
                            ("amendment", "Amendment"),
                            ("finding", "Finding"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("applied", "Applied"),
                            ("superseded", "Superseded"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("apply_payload", models.JSONField(blank=True, default=dict)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.schedule",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agent.scopestate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier", models.PositiveSmallIntegerField(default=0)),
                ("action_type", models.CharField(max_length=40)),
                (
                    "target_model",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("target_pk", models.CharField(blank=True, default="", max_length=40)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True, default="")),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="agent.agentrun",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agent.scopestate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SummarySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule_number", models.CharField(max_length=50)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("authorised", "Authorised"),
                            ("golden", "Golden baseline"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("data", models.JSONField()),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="agent.agentrun",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_snapshots",
                        to="core.schedule",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="agent.scopestate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentAuthorisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_sha256", models.CharField(max_length=64)),
                ("authorised_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authorised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_authorisations",
                        to="core.schedule",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorisations",
                        to="agent.summarysnapshot",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="scopestate",
            constraint=models.UniqueConstraint(
                fields=("account", "channel", "month"), name="agent_scope_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentauthorisation",
            constraint=models.UniqueConstraint(
                fields=("schedule", "snapshot_sha256"), name="agent_auth_unique"
            ),
        ),
    ]
