# Generated by Django 5.2.17 on 2026-09-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="heartbeat",
            name="alert",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="heartbeat",
            name="alert_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="schedulestatus",
            name="makeup_linked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="summarysnapshot",
            name="fingerprint",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="summarysnapshot",
            name="fingerprint_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
