# Generated by Django 5.2.17 on 2026-09-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0002_phase1_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulestatus",
            name="baseline_reason",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
