# Generated by Django 5.2.17 on 2026-09-25 17:42

from django.db import migrations, models


def auto_to_off(apps, schema_editor):
    """Owner decision B: 'auto' is no longer a mode. Any stored 'auto' becomes 'off'."""
    apps.get_model('agent', 'AgentConfig').objects.filter(tc_intake_mode='auto').update(tc_intake_mode='off')


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0003_phase1_2"),
    ]

    operations = [
        migrations.RunPython(auto_to_off, migrations.RunPython.noop),
        migrations.AddField(
            model_name="agentaction",
            name="actor_kind",
            field=models.CharField(
                choices=[
                    ("agent", "Agent"),
                    ("intake_runner", "Intake runner"),
                    ("intake_fetch", "Mail fetch"),
                    ("human", "Person (admin)"),
                ],
                default="agent",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="agentaction",
            name="human_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="intake_fetch_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="min_brand_overlap",
            field=models.FloatField(default=0.6),
        ),
        migrations.AlterField(
            model_name="agentconfig",
            name="tc_intake_mode",
            field=models.CharField(
                choices=[("off", "Off"), ("suggest", "Suggest")],
                default="off",
                max_length=10,
            ),
        ),
    ]
