# Generated by Django 5.2.17 on 2026-09-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0004_phase2"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconfig",
            name="intake_gemini_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="heartbeat",
            name="counts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="heartbeat",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="heartbeat",
            name="last_error_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heartbeat",
            name="last_ok_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
