# Generated by Django 5.2.17 on 2026-09-26 03:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drafts_are_observed(apps, schema_editor):
    """Draft snapshots were taken after committed runs, i.e. what core showed: observed."""
    apps.get_model('agent', 'SummarySnapshot').objects.filter(kind='draft').update(kind='observed')


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0006_clamp_autonomy"),
        ("core", "0041_alter_brandmapping_duration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconfig",
            name="core_fingerprint_timeout_ms",
            field=models.PositiveIntegerField(default=600000),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="db_idle_timeout_ms",
            field=models.PositiveIntegerField(default=60000),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="db_lock_timeout_ms",
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="db_statement_timeout_ms",
            field=models.PositiveIntegerField(default=120000),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="digest_recipients",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role__in": ("super_admin", "admin")},
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="digest_time",
            field=models.TimeField(default=datetime.time(7, 30)),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="max_scopes_per_cycle",
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="observe_every_minutes",
            field=models.PositiveIntegerField(default=360),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="shadow_budget_seconds",
            field=models.PositiveIntegerField(default=1800),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="shadow_window_end",
            field=models.TimeField(default=datetime.time(5, 0)),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="shadow_window_start",
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("cycle", "Cycle"),
                    ("scope", "Scope run"),
                    ("dry_run", "Dry run"),
                    ("golden", "Golden check"),
                    ("audit", "Core audit"),
                    ("shadow_window", "Shadow window"),
                    ("labelled_eval", "Labelled eval"),
                    ("digest", "Digest"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="summarysnapshot",
            name="kind",
            field=models.CharField(
                choices=[
                    ("observed", "Observed"),
                    ("shadow", "Shadow (dry run)"),
                    ("draft", "Draft"),
                    ("authorised", "Authorised"),
                    ("golden", "Golden baseline"),
                ],
                default="observed",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PendingEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("by_brand", models.JSONField(blank=True, default=list)),
                ("totals", models.JSONField(blank=True, default=dict)),
                ("max_abs", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "observed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="agent.summarysnapshot",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.schedule",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_effects",
                        to="agent.scopestate",
                    ),
                ),
                (
                    "shadow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="agent.summarysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FindingLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("code", models.CharField(max_length=40)),
                ("brand", models.CharField(blank=True, default="", max_length=200)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("text", models.TextField(blank=True, default="")),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("actionable", models.BooleanField(default=False)),
                ("open", models.BooleanField(default=True)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("absent_count", models.PositiveSmallIntegerField(default=0)),
                ("reopen_count", models.PositiveSmallIntegerField(default=0)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.CharField(blank=True, default="", max_length=24)),
                ("resolution_evidence", models.JSONField(blank=True, default=dict)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("correct", "Correct"),
                            ("incorrect", "Incorrect"),
                            ("unsure", "Unsure"),
                            ("owner", "Owner label"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                (
                    "label_source",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                ("label_note", models.TextField(blank=True, default="")),
                ("cause_code", models.CharField(blank=True, default="", max_length=40)),
                ("label_as_of", models.DateField(blank=True, null=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agent.agentproposal",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.schedule",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="agent.scopestate",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen", "-id"],
                "indexes": [
                    models.Index(
                        fields=["code", "open"], name="agent_findi_code_24b4f6_idx"
                    )
                ],
            },
        ),
        migrations.RunPython(drafts_are_observed, migrations.RunPython.noop),
    ]
