# Generated by Django 5.2.17 on 2026-09-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0008_phase3_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconfig",
            name="run_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
