# Generated by Django 5.2.17 on 2026-09-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0009_phase3_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconfig",
            name="intake_tool_choice",
            field=models.CharField(
                choices=[
                    ("auto", "Auto (model decides when to call tools)"),
                    (
                        "forced",
                        "Forced (a tool call every turn; submit_decision on the follow-up)",
                    ),
                ],
                default="auto",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="llmcall",
            name="detail",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
