# Generated by Django 5.2.12 on 2026-03-17 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0019_add_sponsorship_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitorUploadBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("row_count", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked batches cannot be deleted — used to preserve historical baselines.",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitor_batches",
                        to="core.account",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competitor_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Competitor Upload Batch",
                "verbose_name_plural": "Competitor Upload Batches",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CompetitorAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_group",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("advertiser", models.CharField(db_index=True, max_length=300)),
                ("product", models.CharField(blank=True, default="", max_length=300)),
                (
                    "advt_theme",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("channel", models.CharField(db_index=True, max_length=200)),
                ("program", models.CharField(blank=True, default="", max_length=300)),
                ("date", models.DateField(db_index=True)),
                ("prog_time", models.CharField(blank=True, default="", max_length=30)),
                ("advt_time", models.CharField(blank=True, default="", max_length=30)),
                ("ad_position", models.IntegerField(blank=True, null=True)),
                ("total_ads", models.IntegerField(blank=True, null=True)),
                ("break_no", models.IntegerField(blank=True, null=True)),
                ("position_in_break", models.IntegerField(blank=True, null=True)),
                ("ads_in_break", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, default="", max_length=50)),
                ("duration", models.IntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitor_ads",
                        to="core.account",
                    ),
                ),
                (
                    "upload_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="competitor.competitoruploadbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competitor Ad",
                "verbose_name_plural": "Competitor Ads",
                "ordering": ["date", "advt_time"],
                "indexes": [
                    models.Index(
                        fields=["account", "date"],
                        name="competitor__account_f587f1_idx",
                    ),
                    models.Index(
                        fields=["account", "advertiser"],
                        name="competitor__account_df8a86_idx",
                    ),
                    models.Index(
                        fields=["account", "channel"],
                        name="competitor__account_c989a3_idx",
                    ),
                    models.Index(
                        fields=["account", "date", "advertiser"],
                        name="competitor__account_de8040_idx",
                    ),
                ],
            },
        ),
    ]
